[server]
    Address        = "127.0.0.1:8081"
    ServerAgent    = "gtoken-demo"
    LogPath        = "./example/sample1/logs"

[gToken]
    # 缓存模式 1 gcache 2 gredis
    CacheMode = 1
    # 是否支持多端登录
    MultiLogin = true

# Redis数据库配置
[redis]
  default = "127.0.0.1:16379,0,soccer"
  cache   = "127.0.0.1:16379,1,soccer?idleTimeout=600"
