log-path = "./logs"
http-port = 80
# 缓存模式 1 gcache 2 gredis
cache-mode = 1

# title设置
[setting]
    title = "token demo"

# WebServer管理
[admin]
    user = "admin"
    pass = "123"

# Redis数据库配置
[redis]
  default = "127.0.0.1:16379,0,soccer"
  cache   = "127.0.0.1:16379,1,soccer?idleTimeout=600"
